name: whatsapp2
description: O projetao do lara.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.0
  firebase_core: ^1.10.6
  firebase_database: ^9.0.4
  contacts_service: ^0.6.3
  flutter_contacts: ^1.1.2
  shared_preferences: ^2.0.11
  camera: ^0.9.4+5
  firebase_auth: ^3.3.5
  flutter_multi_formatter: ^2.5.1
  uuid: ^3.0.5
  postgres: ^2.4.3
  flutter_launcher_icons: ^0.9.2
  share_plus: ^3.0.4
  firebase_storage: ^10.2.6
  image_picker: ^0.8.4+5
  flutter_linkify: ^5.0.2
  cached_network_image: ^3.2.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  path_provider: ^2.0.9
  photo_gallery: ^1.1.1
  permission_handler: ^8.3.0
  open_file: ^3.2.1
  palestine_console: ^0.0.10

dev_dependencies:
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "./assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700