// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjFKSilTzELA1XAyvTPKU9S7n0fmFgDRk',
    appId: '1:271169435175:web:eb824a4ce5190e05578002',
    messagingSenderId: '271169435175',
    projectId: 'teste-5dc23',
    authDomain: 'teste-5dc23.firebaseapp.com',
    databaseURL: 'https://teste-5dc23-default-rtdb.firebaseio.com',
    storageBucket: 'teste-5dc23.appspot.com',
    measurementId: 'G-FF2YQ5KLHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoTmPa8MFTbfdfEKw8FMEpC8w0B1qf2Xg',
    appId: '1:271169435175:android:5389a1a2fd045554578002',
    messagingSenderId: '271169435175',
    projectId: 'teste-5dc23',
    databaseURL: 'https://teste-5dc23-default-rtdb.firebaseio.com',
    storageBucket: 'teste-5dc23.appspot.com',
  );
}
